project:
  type: website
  output-dir: docs
  render:
    - index.qmd
  resources:
    - "*.geojson"
    - "*.csv"
    - "*.jpg"
    - "*.png"

website:
  title: "Fusión Telecom y Telefónica"
  repo-url: https://github.com/pcbbmedia/fusion_ESP

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true 